### PR TITLE
Filter resources NOT having a tag

### PR DESCRIPTION
**Pull request by jckuester**

### CODE REVIEW

**Comment by ghost** [comment]
@jckuester I would be using this feature, let me know if you need some tester :)

**Comment by jckuester** [comment]
@andrea-maruccia-leaseplan sure, is it ok for you to build a custom binary of this branch (simply run `go build` on it) for testing?

**Comment by ghost** [comment]
> @andrea-maruccia-leaseplan sure, is it ok for you to build a custom binary of this branch (simply run `go build` on it) for testing?

yes no problem, should I test it with the latest commit on this branch?

**Comment by jckuester** [comment]
yes. please. I am basically done now.

**Comment by ghost** [comment]
seems to work well!

I used this config for ec2 deletion:

aws_instance:
  - tags:
      NOT(andreatest): .*
then i tried rds db:

aws_db_instance:
  - tags:
      NOT(andreatest): .*
but this didn't work. I think it's ok because in your doc you state that it's not supported.

Nice work :)

**Comment by jckuester** [comment]
@andrea-maruccia-leaseplan just letting you know that in the new release `aws_db_instance` supports tags: https://github.com/cloudetc/awsweeper/releases/tag/v0.9.0. In fact, tag support is repaired for all resources now.

To see which resources support tags, see the list here: https://github.com/cloudetc/awsweeper#supported-resources

**Comment by ghost** [comment]
oh nice @jckuester this is really good news! Is this because you used `awsls`? what is it exactly?

**Comment by jckuester** [comment]
It's an `ls` command for AWS. You can list AWS resources and attributes via the command line instead of using the console. It's my new open-source project: 
```
% awsls -profile myaccount -region us-west-2  -attribute tags "aws_iam_user"

TYPE           ID       REGION      CREATED               TAGS        
aws_iam_user   foo      us-west-2   2018-11-15 19:53:27               
aws_iam_user   janck    us-west-2   2018-06-30 11:25:34   Name=test 
```

**Comment by ghost** [comment]
nice thank you

**Pull request merged**
